Handle page counting errors for protected and locked documents
Ch0ufleur/Projet-LAC pull request #11
Opened 2023-07-26 18:48 UTC by EdwardHealy00

- Changed page counting package to catch errors  
- Implemented basic server side docx validation

2023-07-28 00:31 UTC, Ch0ufleur requested changes

2023-07-28 00:31 UTC, Ch0ufleur commented on client/src/components/catalogue/AddCaseStudy.tsx
> +    "Aucun document n'a été téléversée"
*téléversé

2023-07-28 00:31 UTC, Ch0ufleur commented on server/app/controllers/caseStudy.controller.ts
> +        if(!file || file.mimetype != 'application/vnd.openxmlformats-officedocument.wordprocessingml.document') {
faudrait s'assurer que ce format de mimetype soit  toujours le cas pour tous les fichiers word. si oui c chill, sinon ca pourrait boguer

2023-07-28 20:00 UTC, EdwardHealy00 commented on server/app/controllers/caseStudy.controller.ts
> +        if(!file || file.mimetype != 'application/vnd.openxmlformats-officedocument.wordprocessingml.document') {
J'ai vérifié et c'est le seul mimetype qui existe pour docx.

2023-07-29 17:16 UTC, Ch0ufleur approved these changes

2023-07-29 18:03 UTC, merged